---
title: "Dockets"
format: 
  html:
    toc: true
vignette: >
  %\VignetteIndexEntry{dockets}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = FALSE,
  collapse = FALSE,
  warning = FALSE,
  message = FALSE,
  tidy = FALSE,
  fig.align='center',
  fig.path = "../man/figures/",
  R.options = list(width = 200)
)



# format kable for document type 
kable <- function(...){
  if (knitr::is_latex_output()){
    head(..., 25) |>
      knitr::kable(booktabs = TRUE, format = 'latex') |>
      kableExtra::kable_styling(latex_options = c("striped", "scale_down", "HOLD_position"))
  } else {
    head(..., 50) |>
      dplyr::mutate_all(str_fix) |>
    knitr::kable(escape = TRUE) |>
      kableExtra::kable_styling() |>
      kableExtra::scroll_box(height = "400px")
  }
}

# head <- function(...){
#   head(...) |> 
#   kable() 
# }
```



#### Get dockets from an agency

- `get_dockets("[agency_acronym]")` retrieves dockets for an agency (see official acronyms on regulations.gov)

```{r warning=FALSE, message=FALSE}
# you need an API key
source("~/api-key.R")

library(regulationsdotgov)

devtools::load_all()
```

```{r warning=FALSE}

# get FBI dockets
FBI_dockets <- get_dockets("FBI")

FBI_dockets[[1]]$data |> kable() # FIXME we should not need the [[1]]$data when this no longer returns a list
```
